services:
 frontend:
  container_name: frontend-container
  build: ./frontend
  depends_on:
   - backend
 backend:
  container_name: backend-container
  build: ./backend
 nginx:
  container_name: nginx-reverse-proxy
  image: nginx:latest
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  depends_on:
   - frontend
   - backend

